import io
import pandas as pd


# ============================================================
# EXCEL EXPORT FUNCTIONS
# ============================================================

def create_market_excel_report(snapshot_df, correlation_matrix, selected_commodity, selected_period):
    """
    Crée un fichier Excel en mémoire à partir des données du dashboard.

    snapshot_df : tableau de synthèse des commodities
    correlation_matrix : matrice de corrélation des rendements
    selected_commodity : commodity sélectionnée dans la sidebar
    selected_period : période historique sélectionnée

    La fonction retourne un fichier Excel prêt à être téléchargé dans Streamlit.
    """

    # BytesIO permet de créer un fichier en mémoire,
    # sans l'enregistrer directement sur ton Mac.
    output = io.BytesIO()

    # ExcelWriter permet d'écrire plusieurs feuilles dans un même fichier Excel.
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:

        # ====================================================
        # FEUILLE 1 - MARKET SNAPSHOT
        # ====================================================

        snapshot_df.to_excel(
            writer,
            sheet_name="Market Snapshot",
            index=False
        )

        # ====================================================
        # FEUILLE 2 - CORRELATION MATRIX
        # ====================================================

        if correlation_matrix is not None and not correlation_matrix.empty:
            correlation_matrix.to_excel(
                writer,
                sheet_name="Correlation Matrix"
            )

        # ====================================================
        # FEUILLE 3 - METADATA
        # ====================================================

        metadata_df = pd.DataFrame({
            "Field": [
                "Selected Commodity",
                "Selected Period",
                "Data Frequency",
                "Data Source",
                "Generated By"
            ],
            "Value": [
                selected_commodity,
                selected_period,
                "Daily closing prices",
                "Yahoo Finance via yfinance",
                "Commodity Trading & Hedging Dashboard"
            ]
        })

        metadata_df.to_excel(
            writer,
            sheet_name="Metadata",
            index=False
        )

        # ====================================================
        # MISE EN FORME SIMPLE
        # ====================================================

        workbook = writer.book

        header_format = workbook.add_format({
            "bold": True,
            "bg_color": "#D9EAF7",
            "border": 1
        })

        number_format = workbook.add_format({
            "num_format": "#,##0.00"
        })

        percent_format = workbook.add_format({
            "num_format": "0.00%"
        })

        # Mise en forme de la feuille Market Snapshot
        worksheet = writer.sheets["Market Snapshot"]

        for col_num, value in enumerate(snapshot_df.columns.values):
            worksheet.write(0, col_num, value, header_format)

        worksheet.set_column("A:A", 22)
        worksheet.set_column("B:B", 14, number_format)
        worksheet.set_column("C:F", 18, percent_format)

        # Mise en forme de la feuille Correlation Matrix
        if correlation_matrix is not None and not correlation_matrix.empty:
            worksheet_corr = writer.sheets["Correlation Matrix"]
            worksheet_corr.set_column("A:H", 18, number_format)

        # Mise en forme de la feuille Metadata
        worksheet_meta = writer.sheets["Metadata"]
        worksheet_meta.set_column("A:A", 25)
        worksheet_meta.set_column("B:B", 45)

    # On remet le curseur au début du fichier en mémoire.
    output.seek(0)

    return output

# ============================================================
# HEDGING EXCEL EXPORT
# ============================================================

def create_hedging_excel_report(summary_df, scenario_df, selected_commodity, selected_period):
    """
    Crée un fichier Excel pour le module Hedging Simulator.

    summary_df : tableau de synthèse de la couverture
    scenario_df : tableau d'analyse par scénarios
    selected_commodity : commodity sélectionnée
    selected_period : période historique sélectionnée

    La fonction retourne un fichier Excel prêt à être téléchargé dans Streamlit.
    """

    output = io.BytesIO()

    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:

        # ====================================================
        # FEUILLE 1 - HEDGING SUMMARY
        # ====================================================

        summary_df.to_excel(
            writer,
            sheet_name="Hedging Summary",
            index=False
        )

        # ====================================================
        # FEUILLE 2 - SCENARIO ANALYSIS
        # ====================================================

        scenario_df.to_excel(
            writer,
            sheet_name="Scenario Analysis",
            index=False
        )

        # ====================================================
        # FEUILLE 3 - METADATA
        # ====================================================

        metadata_df = pd.DataFrame({
            "Field": [
                "Selected Commodity",
                "Selected Period",
                "Module",
                "Generated By"
            ],
            "Value": [
                selected_commodity,
                selected_period,
                "Hedging Simulator",
                "Commodity Trading & Hedging Dashboard"
            ]
        })

        metadata_df.to_excel(
            writer,
            sheet_name="Metadata",
            index=False
        )

        # ====================================================
        # MISE EN FORME SIMPLE
        # ====================================================

        workbook = writer.book

        header_format = workbook.add_format({
            "bold": True,
            "bg_color": "#D9EAF7",
            "border": 1
        })

        number_format = workbook.add_format({
            "num_format": "#,##0.00"
        })

        percent_format = workbook.add_format({
            "num_format": "0.00%"
        })

        # Mise en forme Hedging Summary
        worksheet_summary = writer.sheets["Hedging Summary"]

        for col_num, value in enumerate(summary_df.columns.values):
            worksheet_summary.write(0, col_num, value, header_format)

        worksheet_summary.set_column("A:A", 30)
        worksheet_summary.set_column("B:B", 18, number_format)

        # Mise en forme Scenario Analysis
        worksheet_scenario = writer.sheets["Scenario Analysis"]

        for col_num, value in enumerate(scenario_df.columns.values):
            worksheet_scenario.write(0, col_num, value, header_format)

        worksheet_scenario.set_column("A:A", 15, percent_format)
        worksheet_scenario.set_column("B:G", 20, number_format)

        # Mise en forme Metadata
        worksheet_meta = writer.sheets["Metadata"]

        for col_num, value in enumerate(metadata_df.columns.values):
            worksheet_meta.write(0, col_num, value, header_format)

        worksheet_meta.set_column("A:A", 25)
        worksheet_meta.set_column("B:B", 45)

    output.seek(0)

    return output
# ============================================================
# RISK MANAGEMENT EXCEL EXPORT
# ============================================================

def create_risk_excel_report(
    risk_summary_df,
    pnl_df,
    cumulative_pnl_df,
    drawdown_df,
    stress_df,
    selected_commodity,
    selected_period
):
    """
    Crée un fichier Excel pour le module Risk Management.

    risk_summary_df : tableau de synthèse des indicateurs de risque
    pnl_df : distribution historique du P&L
    cumulative_pnl_df : évolution du P&L cumulé
    drawdown_df : série historique des drawdowns
    stress_df : tableau des stress tests
    selected_commodity : commodity sélectionnée
    selected_period : période historique sélectionnée

    La fonction retourne un fichier Excel prêt à être téléchargé dans Streamlit.
    """

    # BytesIO permet de créer un fichier Excel en mémoire.
    # Le fichier n'est pas enregistré directement sur ton Mac.
    output = io.BytesIO()

    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:

        # ====================================================
        # FEUILLE 1 - RISK SUMMARY
        # ====================================================

        risk_summary_df.to_excel(
            writer,
            sheet_name="Risk Summary",
            index=False
        )

        # ====================================================
        # FEUILLE 2 - HISTORICAL P&L
        # ====================================================

        pnl_export = pnl_df.copy()
        pnl_export = pnl_export.reset_index()
        pnl_export.columns = ["Date", "P&L"]

        pnl_export.to_excel(
            writer,
            sheet_name="Historical PnL",
            index=False
        )

        # ====================================================
        # FEUILLE 3 - CUMULATIVE P&L
        # ====================================================

        cumulative_export = cumulative_pnl_df.copy()
        cumulative_export = cumulative_export.reset_index()
        cumulative_export.columns = ["Date", "Cumulative P&L"]

        cumulative_export.to_excel(
            writer,
            sheet_name="Cumulative PnL",
            index=False
        )

        # ====================================================
        # FEUILLE 4 - DRAWDOWN
        # ====================================================

        drawdown_export = drawdown_df.copy()
        drawdown_export = drawdown_export.reset_index()
        drawdown_export.columns = ["Date", "Drawdown"]

        drawdown_export.to_excel(
            writer,
            sheet_name="Drawdown",
            index=False
        )

        # ====================================================
        # FEUILLE 5 - STRESS TESTS
        # ====================================================

        stress_df.to_excel(
            writer,
            sheet_name="Stress Tests",
            index=False
        )

        # ====================================================
        # FEUILLE 6 - METADATA
        # ====================================================

        metadata_df = pd.DataFrame({
            "Field": [
                "Selected Commodity",
                "Selected Period",
                "Module",
                "Data Source",
                "Generated By"
            ],
            "Value": [
                selected_commodity,
                selected_period,
                "Risk Management",
                "Yahoo Finance via yfinance",
                "Commodity Trading & Hedging Dashboard"
            ]
        })

        metadata_df.to_excel(
            writer,
            sheet_name="Metadata",
            index=False
        )

        # ====================================================
        # MISE EN FORME SIMPLE
        # ====================================================

        workbook = writer.book

        header_format = workbook.add_format({
            "bold": True,
            "bg_color": "#D9EAF7",
            "border": 1
        })

        number_format = workbook.add_format({
            "num_format": "#,##0.00"
        })

        percent_format = workbook.add_format({
            "num_format": "0.00%"
        })

        date_format = workbook.add_format({
            "num_format": "yyyy-mm-dd"
        })

        # Feuille Risk Summary
        worksheet_summary = writer.sheets["Risk Summary"]

        for col_num, value in enumerate(risk_summary_df.columns.values):
            worksheet_summary.write(0, col_num, value, header_format)

        worksheet_summary.set_column("A:A", 35)
        worksheet_summary.set_column("B:B", 22, number_format)

        # Feuille Historical P&L
        worksheet_pnl = writer.sheets["Historical PnL"]

        for col_num, value in enumerate(pnl_export.columns.values):
            worksheet_pnl.write(0, col_num, value, header_format)

        worksheet_pnl.set_column("A:A", 15, date_format)
        worksheet_pnl.set_column("B:B", 18, number_format)

        # Feuille Cumulative P&L
        worksheet_cumulative = writer.sheets["Cumulative PnL"]

        for col_num, value in enumerate(cumulative_export.columns.values):
            worksheet_cumulative.write(0, col_num, value, header_format)

        worksheet_cumulative.set_column("A:A", 15, date_format)
        worksheet_cumulative.set_column("B:B", 20, number_format)

        # Feuille Drawdown
        worksheet_drawdown = writer.sheets["Drawdown"]

        for col_num, value in enumerate(drawdown_export.columns.values):
            worksheet_drawdown.write(0, col_num, value, header_format)

        worksheet_drawdown.set_column("A:A", 15, date_format)
        worksheet_drawdown.set_column("B:B", 18, percent_format)

        # Feuille Stress Tests
        worksheet_stress = writer.sheets["Stress Tests"]

        for col_num, value in enumerate(stress_df.columns.values):
            worksheet_stress.write(0, col_num, value, header_format)

        worksheet_stress.set_column("A:A", 18, percent_format)
        worksheet_stress.set_column("B:B", 20, number_format)

        # Feuille Metadata
        worksheet_meta = writer.sheets["Metadata"]

        for col_num, value in enumerate(metadata_df.columns.values):
            worksheet_meta.write(0, col_num, value, header_format)

        worksheet_meta.set_column("A:A", 25)
        worksheet_meta.set_column("B:B", 45)

    # On remet le curseur au début du fichier.
    output.seek(0)

    return output