import io
import pandas as pd


# ============================================================
# EXCEL EXPORT FUNCTIONS
# ============================================================

def create_market_excel_report(snapshot_df, correlation_matrix, selected_commodity, selected_period):
    """
    Crée un fichier Excel en mémoire à partir des données du dashboard.

    snapshot_df : tableau de synthèse des commodities
    correlation_matrix : matrice de corrélation des rendements
    selected_commodity : commodity sélectionnée dans la sidebar
    selected_period : période historique sélectionnée

    La fonction retourne un fichier Excel prêt à être téléchargé dans Streamlit.
    """

    # BytesIO permet de créer un fichier en mémoire,
    # sans l'enregistrer directement sur ton Mac.
    output = io.BytesIO()

    # ExcelWriter permet d'écrire plusieurs feuilles dans un même fichier Excel.
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:

        # ====================================================
        # FEUILLE 1 - MARKET SNAPSHOT
        # ====================================================

        snapshot_df.to_excel(
            writer,
            sheet_name="Market Snapshot",
            index=False
        )

        # ====================================================
        # FEUILLE 2 - CORRELATION MATRIX
        # ====================================================

        if correlation_matrix is not None and not correlation_matrix.empty:
            correlation_matrix.to_excel(
                writer,
                sheet_name="Correlation Matrix"
            )

        # ====================================================
        # FEUILLE 3 - METADATA
        # ====================================================

        metadata_df = pd.DataFrame({
            "Field": [
                "Selected Commodity",
                "Selected Period",
                "Data Frequency",
                "Data Source",
                "Generated By"
            ],
            "Value": [
                selected_commodity,
                selected_period,
                "Daily closing prices",
                "Yahoo Finance via yfinance",
                "Commodity Trading & Hedging Dashboard"
            ]
        })

        metadata_df.to_excel(
            writer,
            sheet_name="Metadata",
            index=False
        )

        # ====================================================
        # MISE EN FORME SIMPLE
        # ====================================================

        workbook = writer.book

        header_format = workbook.add_format({
            "bold": True,
            "bg_color": "#D9EAF7",
            "border": 1
        })

        number_format = workbook.add_format({
            "num_format": "#,##0.00"
        })

        percent_format = workbook.add_format({
            "num_format": "0.00%"
        })

        # Mise en forme de la feuille Market Snapshot
        worksheet = writer.sheets["Market Snapshot"]

        for col_num, value in enumerate(snapshot_df.columns.values):
            worksheet.write(0, col_num, value, header_format)

        worksheet.set_column("A:A", 22)
        worksheet.set_column("B:B", 14, number_format)
        worksheet.set_column("C:F", 18, percent_format)

        # Mise en forme de la feuille Correlation Matrix
        if correlation_matrix is not None and not correlation_matrix.empty:
            worksheet_corr = writer.sheets["Correlation Matrix"]
            worksheet_corr.set_column("A:H", 18, number_format)

        # Mise en forme de la feuille Metadata
        worksheet_meta = writer.sheets["Metadata"]
        worksheet_meta.set_column("A:A", 25)
        worksheet_meta.set_column("B:B", 45)

    # On remet le curseur au début du fichier en mémoire.
    output.seek(0)

    return output